driver:
  name: vagrant

provisioner:
  name: chef_zero

driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]

suites:
  - name: disable
    run_list:
      - recipe[apparmor::default]
      - recipe[minitest-handler::default]
  - name: enable
    run_list:
       - recipe[apparmor::default]
       - recipe[minitest-handler::default]
    attributes:
      apparmor:
        disable: false
