driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: disable
    run_list:
      - recipe[apparmor::default]
    attributes:
      apparmor:
        disable: true
  - name: add
    run_list:
       - recipe[apparmor_test::add]
  - name: remove
    run_list:
       - recipe[apparmor_test::remove]
