driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-15.04
    run_list:
    - recipe[apt::default]   

suites:
  - name: disable
    run_list:
      - recipe[apparmor::default]
    attributes:
      apparmor:
        disable: true
  - name: add
    run_list:
       - recipe[apparmor::default]
       - recipe[apparmor_test::add]
  - name: remove
    run_list:
       - recipe[apparmor::default]
       - recipe[apparmor_test::remove]
